title: wardn
description: Encrypted Bitwarden vault backups
theme: just-the-docs
color_scheme: dark
url: https://rayvn.ink
baseurl: /wardn

nav_external_links:
  - title: GitHub
    url: https://github.com/phoggy/wardn
  - title: rayvn docs
    url: /rayvn

exclude:
  - api/

sass:
  quiet_deps: true
  silence_deprecations: [import]

aux_links:
  "rayvn.ink": "/"
